FROM httpd
COPY ./web/ /usr/local/apache2/htdocs/
EXPOSE 80
#
# Criar a imagem
# docker build -t web_apache .
# Consulta as imagens criadas
# docker image ls
# Subir o servidor, mas fica preso o terminal
# docker run -p 80:80 web_apache
# para liberar o terminal usa-se a opção -d
# docker run -d -p 80:80 web_apache
# listar os containers ativos
# docker ps
# para encerrar o container (CONTAINER ID)
# docker stop 67f56006bbcf 
#
